### ISSUE TITLE
Bidrag til samfundet

### ISSUE THREAD

**Issue by LFalch** [Carditis/Big-booty-Judy#12]
Dette projekt bidrager ikke nok til samfundet. Det synes vi, er for dåååååårligt.

**Comment by LFalch** [comment]
Nåå, det behøver det ikke.

**Comment by RavagoreTV** [comment]
NOAH IS BAD CIV5

**Comment by LFalch** [comment]
> NOAH IS BAD CIV5

@TernishNoddy
